.PHONY: sim
sim:
	python3 robot.py sim


devenvironment:
	sudo pip3 install pyfrc --upgrade
	sudo pip3 install pyrobot --upgrade
	sudo pip3 install robotpy-ctre --upgrade
	sudo pip3 install robotpy-rev --upgrade
